name: Deploy

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to the Github Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.pkg.github.com

      - name: Build Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          image_name: dinossaurz/gpets-web/gpets-web
          image_tag: latest
          dockerfile: app.dockerfile

      - name: Push Image
        run: docker push docker.pkg.github.com/dinossaurz/gpets-web/gpets-web:latest
        env:
          GPETS_SECRET_KEY_BASE: ${{ secrets.GPETS_SECRET_KEY_BASE }}
          RAILS_MASTER_KEY: ${{ secrets.GPETS_SECRET_KEY_BASE }}
          SECRET_KEY_BASE: ${{ secrets.GPETS_SECRET_KEY_BASE }}

      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply kubernetes/app-pod.yml
