name: Deploy to Staging

on:
  pull_request_review:
    types: [submitted,edited]

env:
  CACHE_IMAGE: docker.pkg.github.com/dinossaurz/gpets-web/gpets-web
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: contains(github.event.review.body, 'staging please')

      - name: Login to the Github Registry
        if: contains(github.event.review.body, 'staging please')
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            --username ${{ secrets.DOCKER_USERNAME }} \
            --password-stdin docker.pkg.github.com

      - name: Build Image
        if: contains(github.event.review.body, 'staging please')
        run: |
          docker pull $CACHE_IMAGE:latest
          docker build \
            -f ./app.dockerfile\
            --cache-from $CACHE_IMAGE:latest \
            --tag $CACHE_IMAGE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1\
            "."
        env:
          GPETS_SECRET_KEY_BASE: ${{ secrets.GPETS_SECRET_KEY_BASE }}
          RAILS_MASTER_KEY: ${{ secrets.GPETS_SECRET_KEY_BASE }}
          SECRET_KEY_BASE: ${{ secrets.GPETS_SECRET_KEY_BASE }}

      - name: Push Image
        if: contains(github.event.review.body, 'staging please')
        run: docker push $CACHE_IMAGE:latest

      - name: Staging Deploy
        if: contains(github.event.review.body, 'staging please')
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout restart deploy gpets-web -n staging

      - name: Slack notification
        if: contains(github.event.review.body, 'staging please')
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_MESSAGE: 'Finished!'
          SLACK_TITLE: 'Deploy to Staging'
          SLACK_USERNAME: 'Botsauro'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_COLOR: '#F0E68C'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
